name: Run test

on:
  push:
    branches:
      - '**'
      - '!main'
env:
  ZUORA_ENDPOINT: https://rest.apisandbox.zuora.com
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Run bundle install
        run:  bundle install
      - name: Run rubocop
        run:  bundle exec rubocop
      - name: Run rspec
        run:  bundle exec rspec
